/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as OnboardingIndexImport } from './routes/onboarding/index'
import { Route as AppDashboardImport } from './routes/_app/dashboard'
import { Route as AppTutoresIndexImport } from './routes/_app/tutores/index'
import { Route as AppServicosIndexImport } from './routes/_app/servicos/index'
import { Route as AppRelatoriosIndexImport } from './routes/_app/relatorios/index'
import { Route as AppProfissionaisIndexImport } from './routes/_app/profissionais/index'
import { Route as AppPlanosIndexImport } from './routes/_app/planos/index'
import { Route as AppPetsIndexImport } from './routes/_app/pets/index'
import { Route as AppFinanceiroIndexImport } from './routes/_app/financeiro/index'
import { Route as AppConfiguracoesIndexImport } from './routes/_app/configuracoes/index'
import { Route as AppCaixaIndexImport } from './routes/_app/caixa/index'
import { Route as AppAgendaIndexImport } from './routes/_app/agenda/index'
import { Route as AppPetsPetIdImport } from './routes/_app/pets/$petId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingIndexRoute = OnboardingIndexImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

const AppTutoresIndexRoute = AppTutoresIndexImport.update({
  id: '/tutores/',
  path: '/tutores/',
  getParentRoute: () => AppRoute,
} as any)

const AppServicosIndexRoute = AppServicosIndexImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => AppRoute,
} as any)

const AppRelatoriosIndexRoute = AppRelatoriosIndexImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => AppRoute,
} as any)

const AppProfissionaisIndexRoute = AppProfissionaisIndexImport.update({
  id: '/profissionais/',
  path: '/profissionais/',
  getParentRoute: () => AppRoute,
} as any)

const AppPlanosIndexRoute = AppPlanosIndexImport.update({
  id: '/planos/',
  path: '/planos/',
  getParentRoute: () => AppRoute,
} as any)

const AppPetsIndexRoute = AppPetsIndexImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => AppRoute,
} as any)

const AppFinanceiroIndexRoute = AppFinanceiroIndexImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => AppRoute,
} as any)

const AppConfiguracoesIndexRoute = AppConfiguracoesIndexImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => AppRoute,
} as any)

const AppCaixaIndexRoute = AppCaixaIndexImport.update({
  id: '/caixa/',
  path: '/caixa/',
  getParentRoute: () => AppRoute,
} as any)

const AppAgendaIndexRoute = AppAgendaIndexImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => AppRoute,
} as any)

const AppPetsPetIdRoute = AppPetsPetIdImport.update({
  id: '/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/pets/$petId': {
      id: '/_app/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof AppPetsPetIdImport
      parentRoute: typeof AppImport
    }
    '/_app/agenda/': {
      id: '/_app/agenda/'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/caixa/': {
      id: '/_app/caixa/'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AppCaixaIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/configuracoes/': {
      id: '/_app/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/financeiro/': {
      id: '/_app/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/pets/': {
      id: '/_app/pets/'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof AppPetsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/planos/': {
      id: '/_app/planos/'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AppPlanosIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/profissionais/': {
      id: '/_app/profissionais/'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof AppProfissionaisIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/relatorios/': {
      id: '/_app/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/servicos/': {
      id: '/_app/servicos/'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AppServicosIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/tutores/': {
      id: '/_app/tutores/'
      path: '/tutores'
      fullPath: '/tutores'
      preLoaderRoute: typeof AppTutoresIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPetsPetIdRoute: typeof AppPetsPetIdRoute
  AppAgendaIndexRoute: typeof AppAgendaIndexRoute
  AppCaixaIndexRoute: typeof AppCaixaIndexRoute
  AppConfiguracoesIndexRoute: typeof AppConfiguracoesIndexRoute
  AppFinanceiroIndexRoute: typeof AppFinanceiroIndexRoute
  AppPetsIndexRoute: typeof AppPetsIndexRoute
  AppPlanosIndexRoute: typeof AppPlanosIndexRoute
  AppProfissionaisIndexRoute: typeof AppProfissionaisIndexRoute
  AppRelatoriosIndexRoute: typeof AppRelatoriosIndexRoute
  AppServicosIndexRoute: typeof AppServicosIndexRoute
  AppTutoresIndexRoute: typeof AppTutoresIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPetsPetIdRoute: AppPetsPetIdRoute,
  AppAgendaIndexRoute: AppAgendaIndexRoute,
  AppCaixaIndexRoute: AppCaixaIndexRoute,
  AppConfiguracoesIndexRoute: AppConfiguracoesIndexRoute,
  AppFinanceiroIndexRoute: AppFinanceiroIndexRoute,
  AppPetsIndexRoute: AppPetsIndexRoute,
  AppPlanosIndexRoute: AppPlanosIndexRoute,
  AppProfissionaisIndexRoute: AppProfissionaisIndexRoute,
  AppRelatoriosIndexRoute: AppRelatoriosIndexRoute,
  AppServicosIndexRoute: AppServicosIndexRoute,
  AppTutoresIndexRoute: AppTutoresIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/pets/$petId': typeof AppPetsPetIdRoute
  '/agenda': typeof AppAgendaIndexRoute
  '/caixa': typeof AppCaixaIndexRoute
  '/configuracoes': typeof AppConfiguracoesIndexRoute
  '/financeiro': typeof AppFinanceiroIndexRoute
  '/pets': typeof AppPetsIndexRoute
  '/planos': typeof AppPlanosIndexRoute
  '/profissionais': typeof AppProfissionaisIndexRoute
  '/relatorios': typeof AppRelatoriosIndexRoute
  '/servicos': typeof AppServicosIndexRoute
  '/tutores': typeof AppTutoresIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/pets/$petId': typeof AppPetsPetIdRoute
  '/agenda': typeof AppAgendaIndexRoute
  '/caixa': typeof AppCaixaIndexRoute
  '/configuracoes': typeof AppConfiguracoesIndexRoute
  '/financeiro': typeof AppFinanceiroIndexRoute
  '/pets': typeof AppPetsIndexRoute
  '/planos': typeof AppPlanosIndexRoute
  '/profissionais': typeof AppProfissionaisIndexRoute
  '/relatorios': typeof AppRelatoriosIndexRoute
  '/servicos': typeof AppServicosIndexRoute
  '/tutores': typeof AppTutoresIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/pets/$petId': typeof AppPetsPetIdRoute
  '/_app/agenda/': typeof AppAgendaIndexRoute
  '/_app/caixa/': typeof AppCaixaIndexRoute
  '/_app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/_app/financeiro/': typeof AppFinanceiroIndexRoute
  '/_app/pets/': typeof AppPetsIndexRoute
  '/_app/planos/': typeof AppPlanosIndexRoute
  '/_app/profissionais/': typeof AppProfissionaisIndexRoute
  '/_app/relatorios/': typeof AppRelatoriosIndexRoute
  '/_app/servicos/': typeof AppServicosIndexRoute
  '/_app/tutores/': typeof AppTutoresIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/pets/$petId'
    | '/agenda'
    | '/caixa'
    | '/configuracoes'
    | '/financeiro'
    | '/pets'
    | '/planos'
    | '/profissionais'
    | '/relatorios'
    | '/servicos'
    | '/tutores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/dashboard'
    | '/onboarding'
    | '/pets/$petId'
    | '/agenda'
    | '/caixa'
    | '/configuracoes'
    | '/financeiro'
    | '/pets'
    | '/planos'
    | '/profissionais'
    | '/relatorios'
    | '/servicos'
    | '/tutores'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/onboarding/'
    | '/_app/pets/$petId'
    | '/_app/agenda/'
    | '/_app/caixa/'
    | '/_app/configuracoes/'
    | '/_app/financeiro/'
    | '/_app/pets/'
    | '/_app/planos/'
    | '/_app/profissionais/'
    | '/_app/relatorios/'
    | '/_app/servicos/'
    | '/_app/tutores/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/login",
        "/onboarding/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/dashboard",
        "/_app/pets/$petId",
        "/_app/agenda/",
        "/_app/caixa/",
        "/_app/configuracoes/",
        "/_app/financeiro/",
        "/_app/pets/",
        "/_app/planos/",
        "/_app/profissionais/",
        "/_app/relatorios/",
        "/_app/servicos/",
        "/_app/tutores/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_app/dashboard": {
      "filePath": "_app/dashboard.tsx",
      "parent": "/_app"
    },
    "/onboarding/": {
      "filePath": "onboarding/index.tsx"
    },
    "/_app/pets/$petId": {
      "filePath": "_app/pets/$petId.tsx",
      "parent": "/_app"
    },
    "/_app/agenda/": {
      "filePath": "_app/agenda/index.tsx",
      "parent": "/_app"
    },
    "/_app/caixa/": {
      "filePath": "_app/caixa/index.tsx",
      "parent": "/_app"
    },
    "/_app/configuracoes/": {
      "filePath": "_app/configuracoes/index.tsx",
      "parent": "/_app"
    },
    "/_app/financeiro/": {
      "filePath": "_app/financeiro/index.tsx",
      "parent": "/_app"
    },
    "/_app/pets/": {
      "filePath": "_app/pets/index.tsx",
      "parent": "/_app"
    },
    "/_app/planos/": {
      "filePath": "_app/planos/index.tsx",
      "parent": "/_app"
    },
    "/_app/profissionais/": {
      "filePath": "_app/profissionais/index.tsx",
      "parent": "/_app"
    },
    "/_app/relatorios/": {
      "filePath": "_app/relatorios/index.tsx",
      "parent": "/_app"
    },
    "/_app/servicos/": {
      "filePath": "_app/servicos/index.tsx",
      "parent": "/_app"
    },
    "/_app/tutores/": {
      "filePath": "_app/tutores/index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
